### PR TITLE
fix(sema): add handling for event/error failures

### LINKED ISSUE #659: Improve printing of events and errors in `TySolcPrinter`
### Describe the feature

Currently `TySolcPrinter` prints events and errors as functions:

https://github.com/paradigmxyz/solar/blob/f1325b335fb5e03daa622a103026ed31d6c387de/crates/sema/src/ty/print.rs#L339-L340

Example:

```
error: wrong number of arguments for function A.B(bool): expected 1, found 0
  ╭▸ tmp/event.sol:8:9
  │
8 │         B();
  │         ━
  │
  ╰ note: created at crates/sema/src/typeck/checker.rs:171:34,
          emitted at crates/sema/src/typeck/checker.rs:178:34
```

These should be printed as `event A.B(bool)` and `error A.B(bool)` respectively.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by figtracer**
fixes #659 

```bash
error: wrong number of arguments for error AmazingContract.SimpleError(bool): expected 1, found 0
  ╭▸ testdata/test.sol:9:9
  │
9 │         SimpleError();
  │         ━━━━━━━━━━━━━
  │
  ╰ note: created at crates/sema/src/typeck/checker.rs:171:34,
          emitted at crates/sema/src/typeck/checker.rs:178:34

error: wrong number of arguments for event AmazingContract.SimpleEvent(bool): expected 1, found 2
   ╭▸ testdata/test.sol:10:9
   │
10 │         SimpleEvent(true, false);
   │         ━━━━━━━━━━━━━━━━━━━━━━━━
   │
   ╰ note: created at crates/sema/src/typeck/checker.rs:171:34,
           emitted at crates/sema/src/typeck/checker.rs:178:34

error: aborting due to 2 previous errors
```

### CODE REVIEW

File: crates/sema/src/typeck/checker.rs [hunk 1]
```diff
@@ -164,9 +164,20 @@ impl<'gcx> TypeChecker<'gcx> {
...
+                                    "wrong number of arguments for {}: expected {}, found {}",
+                                    callee_ty.display(self.gcx),
+                                    params.len(),
+                                    arg_count
+                                ))
+                                .span(expr.span)
+                                .emit();
+                        }
+                        callee_ty
                     }
```
Comment (onbjerg) [inline crates/sema/src/typeck/checker.rs]: hey, please remove this part as it is unrelated to the task at hand, thanks!

**Review by onbjerg — CHANGES_REQUESTED** [review]
looks good, but please keep the pr on topic:)

File: crates/sema/src/typeck/checker.rs (hunk 1 above)
Comment (figtracer) [reply crates/sema/src/typeck/checker.rs]: my bad, i thought it was about the whole implementation...on it!

Comment (onbjerg) [reply crates/sema/src/typeck/checker.rs]: no worries-i'm already working on proper typeck for events and errors, it's requires a bit of plumbing to cover the full spectrum

**Review by onbjerg — APPROVED** [review]
