### PR TITLE
feat(sema): implement explicit conversions for fixed-size byte arrays

### LINKED ISSUE #612: Fixed size byte explicit conversions
### Describe the feature

Fixed size bytes are convertible to and from all sizes. A smaller size truncates the bytes on the right-hand side. A larger size right-pads the value with 0s.

Fixed size bytes can also be explicitly converted to integers of the same size.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by onbjerg**
Add explicit type conversion support for:
- FixedBytes to FixedBytes (any size)
- FixedBytes to UInt (same size only)
- UInt to FixedBytes (same size only)

Signed integers are not allowed per Solidity spec.

Closes #612

### CODE REVIEW

**Review by DaniPopes — APPROVED** [review]

File: crates/sema/src/ty/ty.rs [hunk 1]
```diff
@@ -445,10 +445,38 @@ impl<'gcx> Ty<'gcx> {
...
+
+            // FixedBytes to UInt: same size only (signed integers not allowed).
+            // See: <https://docs.soliditylang.org/en/latest/types.html#explicit-conversions>
+            (
+                TyKind::Elementary(ElementaryType::FixedBytes(size_from)),
+                TyKind::Elementary(ElementaryType::UInt(size_to)),
+            ) if size_from == size_to => Ok(()),
+
+            // UInt to FixedBytes: same size only (signed integers not allowed).
+            // See: <https://docs.soliditylang.org/en/latest/types.html#explicit-conversions>
```
Comment (DaniPopes) [inline crates/sema/src/ty/ty.rs]: should hoist this repeated link to the function docs
