### PR TITLE
feat(sema): implicit bytes literal conversion to bytes dynamic/fixed

### LINKED ISSUE #640: Bytes literal implicit conversion
### Describe the feature

Allow implicitly converting byte literals to bytes (dynamic, sized). See https://docs.soliditylang.org/en/latest/types.html#index-34

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dipanshuhappy**
Resolves #640 
When I run solc on the test case the error message was 
```
TypeError: Type literal_string "ab" is not implicitly convertible to expected type bytes1. Literal is larger than the type.
```
Solar was giving 
```
mismatched types
```
Happy to work on making the error more descriptive on another issue. If so let me know

### CODE REVIEW

**Comment by DaniPopes** [comment]
You can merge main and you'll have an error enum you can add a variant to improve the error message

File: crates/sema/src/ty/ty.rs [hunk 1]
```diff
@@ -529,6 +529,16 @@ impl<'gcx> Ty<'gcx> {
...
                 }
             }
+            // byte literal -> bytesN/bytes
+            // See: <https://docs.soliditylang.org/en/latest/types.html#index-34>
+            (StringLiteral(_, _), Elementary(Bytes)) => Ok(()),
+            (StringLiteral(_, size_from), Elementary(FixedBytes(size_to))) => {
+                if size_from.bytes() <= size_to.bytes() {
+                    Ok(())
+                } else {
+                    Result::Err(TyConvertError::InvalidConversion)
```
Comment (DaniPopes) [inline crates/sema/src/ty/ty.rs]: can you add a new variant to match the solc error message?
