### PR TITLE
fix(lowering): bring `this` and `super` into scope for constructor inheritance

### LINKED ISSUE #569: bug(lowering): unresolved symbol `this` in contract constructor inheritance
a user raised this issue in foundry https://github.com/foundry-rs/foundry/issues/12047 pointing out that solar fails to process this code:

```solidity
contract Foo {
    constructor(Bar) {}
}

contract Bar is Foo(this) {}
```

the error message seems to indicate that this is a problem in the lowering phase:

```
error: unresolved symbol `this`
 --> src/Aaa.sol:8:29
  |
8 | contract Bar is Foo(address(this)) {}
  |                             ^^^^
```

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

aims to close #569 by creating a manual scope in "base scope" with only `this`

### CODE REVIEW

File: crates/sema/src/ast_lowering/resolve.rs [hunk 1]
```diff
@@ -411,7 +411,16 @@ impl<'gcx> ResolveContext<'gcx> {
...
+            // Initialize without contract scope, but manually add a local scope with only `this` to
+            // allows builtins to be accessible in base constructor arguments while keeping state
+            // variables inaccessible.
             self.init(contract.source, None, None);
+            self.scopes.enter();
+            let span = Span::DUMMY;
+            let this_decl = Declaration { res: Res::Builtin(Builtin::This), span };
+            self.scopes.current_scope().declare_unchecked(sym::this, this_decl);
+
             self.hir.contracts[c_id].bases_args = self.arena.alloc_from_iter(
```
Comment (DaniPopes) [inline crates/sema/src/ast_lowering/resolve.rs]: please move all the code inside of the scope into a new method, this currently doesn't cover the `continue`

File: crates/sema/src/ast_lowering/resolve.rs [hunk 2]
```diff
@@ -407,70 +407,86 @@ impl<'gcx> ResolveContext<'gcx> {
...
-                        span: ast_base.span(),
-                        id: base_id.into(),
-                        args: self.lower_call_args(&ast_base.arguments),
-                    },
-                ),
-            );
-            let contract = self.hir.contract(c_id);
+            self.scopes.enter();
+            let this_decl = Declaration { res: Res::Builtin(Builtin::This), span: Span::DUMMY };
+            self.scopes.current_scope().declare_unchecked(sym::this, this_decl);
```
Comment (DaniPopes) [inline crates/sema/src/ast_lowering/resolve.rs]: what about `super`?

Comment (0xrusowsky) [reply crates/sema/src/ast_lowering/resolve.rs]: you are right, i ran:
```sh
solc - <<EOF
  // SPDX-License-Identifier: MIT
  pragma solidity ^0.8.0;

  abstract contract WithArgs {
      constructor(uint256 b) {}
  }

  abstract contract WithAddrArgs {
      constructor(address) {}
  }

  abstract contract Base {
      function getValue() public virtual returns (uint) { return 42; }
  }

  contract M is Base, WithAddrArgs(address(this)), WithArgs(super.getValue()) {
      constructor() {}
  }
EOF
```

and it looks like solc also supports both `this` and `super`
